version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: .dockerfile
    volumes:
      - './:/app'
      - '/app/node_modules'
      - '/app/dist'
    ports:
      - '8080:8080'